In [1]:
import numpy as np
import pandas as pd 
from datetime import datetime

In [6]:
df1 = pd.read_csv("../data/ASOS_month(종관기상관측)).csv",encoding='cp949')
df1

,지점,지점명,일시,평균기온(°C),최고기온(°C),최저기온(°C),평균상대습도(%),월합강수량(00~24h만)(mm),일최다강수량(mm),1시간최다강수량(mm),10분최다강수량(mm),평균풍속(m/s),최대풍속(m/s),최대순간풍속(m/s),평균운량(1/10),합계 일조시간(hr),합계 일사량(MJ/m2),최심적설(cm)
0,90,속초,2000-01,-0.4,9.9,-10.9,56.0,90.2,31.5,NaN,NaN,2.2,16.6,22.6,4.8,150.0,NaN,32.8
1,90,속초,2000-02,-0.1,9.2,-8.6,41.0,8.4,8.3,NaN,NaN,2.9,9.8,13.0,2.5,225.7,NaN,13.8
2,90,속초,2000-03,6.9,18.5,-4.2,45.0,8.7,4.9,NaN,NaN,3.6,11.5,13.6,4.1,206.3,NaN,0.4
3,90,속초,2000-04,11.2,24.1,2.4,55.0,23.4,9.5,3.8,1.1,3.9,14.5,26.8,5.0,200.9,NaN,NaN
4,90,속초,2000-05,14.3,30.5,6.2,79.0,71.0,21.1,7.0,3.0,2.6,9.7,14.9,6.4,156.8,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24837,295,남해,2023-05,18.0,29.1,7.9,75.0,415.5,258.3,41.3,10.2,1.4,7.5,20.9,6.2,186.0,NaN,NaN
24838,295,남해,2023-06,22.5,30.6,15.8,78.0,364.9,129.3,74.5,21.0,1.2,5.5,12.3,6.3,192.6,NaN,NaN
24839,295,남해,2023-07,25.4,33.5,20.2,88.0,709.8,237.8,56.5,15.0,1.1,7.3,14.4,7.2,99.8,NaN,NaN
24840,295,남해,2023-08,27.1,35.1,22.4,82.0,404.2,130.2,28.9,11.4,NaN,7.4,15.9,5.1,206.7,NaN,NaN
24841,295,남해,2023-09,23.8,31.1,17.1,82.0,280.9,102.2,37.2,20.9,1.4,5.8,12.8,6.0,148.8,NaN,NaN

In [7]:
df2 = pd.read_csv("../data/ulsan_fcst_data(일기예보).csv",encoding='cp949')
df2

,Forecast time,forecast,Temperature,Humidity,WindSpeed,WindDirection,Cloud
0,2018-03-01 11:00:00,4.0,8.0,20.0,14.0,298.0,2.0
1,2018-03-01 11:00:00,7.0,4.0,20.0,4.3,298.0,2.0
2,2018-03-01 11:00:00,10.0,3.0,30.0,1.9,309.0,2.0
3,2018-03-01 11:00:00,13.0,0.0,40.0,1.5,318.0,2.0
4,2018-03-01 11:00:00,16.0,-1.0,45.0,1.8,308.0,2.0
...,...,...,...,...,...,...,...
162203,2021-03-01 08:00:00,52.0,9.0,45.0,3.1,83.0,3.0
162204,2021-03-01 08:00:00,55.0,9.0,45.0,3.0,111.0,3.0
162205,2021-03-01 08:00:00,58.0,8.0,55.0,2.2,122.0,3.0
162206,2021-03-01 08:00:00,61.0,6.0,65.0,0.9,131.0,3.0
162207,2021-03-01 08:00:00,64.0,4.0,80.0,0.7,188.0,3.0

일출일몰시간 데이터로 낮밤 구분
+출몰시간

Forecast : 예보 시간
forecast : 예보 시간+forecast => 실제 시간
예보시간 고정

In [8]:
df1['지점명'].unique()

array(['속초', '북춘천', '철원', '동두천', '파주', '대관령', '춘천', '백령도', '북강릉', '강릉',
       '동해', '서울', '인천', '원주', '울릉도', '수원', '영월', '충주', '서산', '울진', '청주',
       '대전', '추풍령', '안동', '상주', '포항', '군산', '대구', '전주', '울산', '창원', '광주',
       '부산', '통영', '무안', '목포', '여수', '흑산도', '완도', '고창', '순천', '진도(첨찰산)',
       '대구(기)', '홍성', '서청주', '제주', '고산', '성산', '서귀포', '진주', '강화', '양평',
       '이천', '인제', '홍천', '태백', '정선군', '제천', '보은', '천안', '보령', '부여', '금산',
       '세종', '부안', '임실', '정읍', '남원', '장수', '고창군', '영광군', '김해시', '순창군',
       '북창원', '주암', '양산시', '보성군', '강진군', '장흥', '해남', '고흥', '의령군', '함양군',
       '성산포', '광양시', '진도군', '봉화', '영주', '문경', '청송군', '영덕', '의성', '구미',
       '영천', '경주시', '거창', '합천', '밀양', '산청', '거제', '남해'], dtype=object)

In [9]:
df1.isna().sum()

지점                        0
지점명                       0
일시                        0
평균기온(°C)                 29
최고기온(°C)                  0
최저기온(°C)                  0
평균상대습도(%)                33
월합강수량(00~24h만)(mm)       30
일최다강수량(mm)               30
1시간최다강수량(mm)          10235
10분최다강수량(mm)          10273
평균풍속(m/s)                36
최대풍속(m/s)                 8
최대순간풍속(m/s)               8
평균운량(1/10)            10141
합계 일조시간(hr)              77
합계 일사량(MJ/m2)         15271
최심적설(cm)              21200
dtype: int64

In [11]:
df1['최심적설(cm)'].describe()

count    3642.000000
mean        7.940637
std        12.508968
min         0.000000
25%         1.600000
50%         4.400000
75%         9.000000
max       162.800000
Name: 최심적설(cm), dtype: float64